# Generated by Django 3.1.4 on 2021-01-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_auto_20201220_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '패스트캠퍼스 사용자', 'verbose_name_plural': '패스트캠퍼스 사용자'},
        ),
        migrations.AlterModelTable(
            name='fcuser',
            table='fcuser_fcuser',
        ),
    ]
