# Generated by Django 3.1.4 on 2021-01-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0005_auto_20210106_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fcuser',
            old_name='dttm',
            new_name='registered_dttm',
        ),
    ]
