# Generated by Django 3.1.5 on 2021-01-14 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pwd',
            new_name='password',
        ),
    ]
