# Generated by Django 3.1.4 on 2021-01-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_auto_20210104_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.EmailField(default='test@gamil.com', max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
    ]
