# Generated by Django 3.1.4 on 2021-01-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0006_auto_20210106_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
    ]
