# Generated by Django 3.1.4 on 2021-01-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='tags',
        ),
    ]
